### ISSUE TITLE
what is an example of a zcap http header?

### ISSUE THREAD

**Issue by gobengo** [w3c-ccg/zcap-spec#48]
[S1.5.2](https://w3c-ccg.github.io/zcap-spec/#invoke-delegate-capability) says:
>  When invoking a delegated zcap using an HTTP signature, a capability-invocation header must be included that includes the full delegated zcap in a capability parameter by serializing it to JSON, gzipping the result, and then base64url-encoding the gzipped JSON. 

When I read this, I expected that meant that the header is like:
```http
capability-invocation: {base64url(gzip(json({capability: theCapability}))}
```

However, it would appear that some implementations expect something different, e.g. [ezcap](https://github.com/digitalbazaar/http-signature-zcap-verify/blob/main/lib/index.js#L143) appears to parse the header value in the same way it would parse an HTTP Signautre header value, i.e. it expects
```http
capability-invocation: zcap capability="{base64url(gzip(json(theCapability}))}"
```

Which is correct per the spec?

If the latter, the spec text could be improved and an example in an appendix would be invaluable

**Comment by dlongley** [comment]
The latter is correct. The spec should be improved in the way you state.

**Comment by gobengo** [comment]
ty
